import type { Config } from "tailwindcss";

const config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./views/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx,scss,css}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "var(--pc-page-gutter)",
      screens: {
        "2xl": "1320px",
      },
    },
    extend: {
      spacing: {
        page: "var(--pc-page-gutter)",
      },
      maxWidth: {
        reading: "var(--pc-reading-max)",
      },
      boxShadow: {
        surface: "var(--pc-shadow-surface)",
        elevated: "var(--pc-shadow-elevated)",
        inset: "var(--pc-shadow-inset)",
      },
      fontFamily: {
        sans: [
          "var(--font-sans)",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Roboto",
          "Arial",
          "sans-serif",
        ],
        brand: [
          "var(--font-brand)",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Roboto",
          "Arial",
          "sans-serif",
        ],
        heading: [
          "var(--font-brand)",
          "var(--font-sans)",
          "system-ui",
          "sans-serif",
        ],
        body: [
          "var(--font-sans)",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        mono: [
          "var(--font-mono)",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "monospace",
        ],
      },
      colors: {
        blue: {
          500: "rgb(var(--blue-500-rgb) / <alpha-value>)",
          600: "rgb(var(--blue-600-rgb) / <alpha-value>)",
          700: "rgb(var(--blue-700-rgb) / <alpha-value>)",
          800: "rgb(var(--blue-800-rgb) / <alpha-value>)",
          900: "rgb(var(--blue-900-rgb) / <alpha-value>)",
        },
        brand: {
          500: "rgb(var(--pc-blue-500-rgb) / <alpha-value>)",
          600: "rgb(var(--pc-blue-600-rgb) / <alpha-value>)",
          900: "rgb(var(--pc-blue-900-rgb) / <alpha-value>)",
        },
        ink: {
          950: "rgb(var(--pc-gray-950-rgb) / <alpha-value>)",
          900: "rgb(var(--pc-gray-900-rgb) / <alpha-value>)",
          800: "rgb(var(--pc-gray-800-rgb) / <alpha-value>)",
          700: "rgb(var(--pc-gray-700-rgb) / <alpha-value>)",
          600: "rgb(var(--pc-gray-600-rgb) / <alpha-value>)",
          500: "rgb(var(--pc-gray-500-rgb) / <alpha-value>)",
          400: "rgb(var(--pc-gray-400-rgb) / <alpha-value>)",
          300: "rgb(var(--pc-gray-300-rgb) / <alpha-value>)",
          200: "rgb(var(--pc-gray-200-rgb) / <alpha-value>)",
          100: "rgb(var(--pc-gray-100-rgb) / <alpha-value>)",
          50: "rgb(var(--pc-gray-50-rgb) / <alpha-value>)",
        },
        background: "rgb(var(--pc-bg-rgb) / <alpha-value>)",
        surface: "rgb(var(--pc-surface-rgb) / <alpha-value>)",
        "surface-soft": "rgb(var(--pc-surface-soft-rgb) / <alpha-value>)",
        "surface-elevated": "rgb(var(--pc-surface-elevated-rgb) / <alpha-value>)",
        text: "rgb(var(--pc-text-rgb) / <alpha-value>)",
        muted: "rgb(var(--pc-muted-rgb) / <alpha-value>)",
        "muted-soft": "rgb(var(--pc-muted-foreground-soft-rgb) / <alpha-value>)",
        border: "rgb(var(--pc-border-rgb) / <alpha-value>)",
        "border-subtle": "rgb(var(--pc-border-subtle-rgb) / <alpha-value>)",
        "border-strong": "rgb(var(--pc-border-strong-rgb) / <alpha-value>)",
        primary: "rgb(var(--pc-blue-600-rgb) / <alpha-value>)",
        secondary: "rgb(var(--pc-blue-500-rgb) / <alpha-value>)",
        "primary-foreground": "rgb(var(--pc-primary-foreground-rgb) / <alpha-value>)",
        ring: "rgb(var(--pc-ring-rgb) / <alpha-value>)",
        card: "rgb(var(--pc-surface-rgb) / <alpha-value>)",
        "card-foreground": "rgb(var(--pc-text-rgb) / <alpha-value>)",
        input: "rgb(var(--pc-border-rgb) / <alpha-value>)",
        destructive: "rgb(var(--pc-destructive-rgb) / <alpha-value>)",
        "destructive-foreground": "rgb(var(--pc-destructive-foreground-rgb) / <alpha-value>)",
        black1: "rgb(var(--pc-gray-950-rgb) / <alpha-value>)",
        foreground: "rgb(var(--pc-text-rgb) / <alpha-value>)",
        "muted-foreground": "rgb(var(--pc-muted-foreground-rgb) / <alpha-value>)",
        prochat: {
          50: "var(--blue-50)",
          500: "var(--blue-500)",
          600: "var(--blue-600)",
          700: "var(--blue-700)",
          800: "var(--blue-800)",
          900: "var(--blue-900)",
        },
        gray: {
          0: "var(--gray-0)",
          50: "var(--gray-50)",
          100: "var(--gray-100)",
          200: "var(--gray-200)",
          300: "var(--gray-300)",
          400: "var(--gray-400)",
          500: "var(--gray-500)",
          600: "var(--gray-600)",
          700: "var(--gray-700)",
          800: "var(--gray-800)",
          900: "var(--gray-900)",
          950: "var(--gray-0)",
        },
      },
      backgroundImage: {
        banner: "url('/assets/banner.svg')",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;

export default config;
